# Generated by Django 4.2.7 on 2023-12-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jog',
            name='num',
        ),
    ]
